"""create streams table

Revision ID: 29a286192f31
Revises: f63bfcbfad78
Create Date: 2026-07-26 22:01:36.427990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a286192f31'
down_revision: Union[str, Sequence[str], None] = 'f63bfcbfad78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('streams',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('YOUTUBE', 'TWITCH', 'KICK', 'VIMEO', 'CUSTOM', 'UNKNOWN', name='providertype'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('destination_rtmp_url', sa.Text(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('auto_start', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'READY', 'STARTING', 'RUNNING', 'STOPPING', 'STOPPED', 'ERROR', name='streamstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streams_uuid'), 'streams', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_streams_uuid'), table_name='streams')
    op.drop_table('streams')
    # ### end Alembic commands ###
