"""create stream sessions

Revision ID: 50e70d24c1b6
Revises: 29a286192f31
Create Date: 2026-07-26 22:13:47.280964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '50e70d24c1b6'
down_revision: Union[str, Sequence[str], None] = '29a286192f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_sessions',
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column(
        'status',
        postgresql.ENUM(
            'DRAFT',
            'READY',
            'STARTING',
            'RUNNING',
            'STOPPING',
            'STOPPED',
            'ERROR',
            name='streamstatus',
            create_type=False
        ),
        nullable=False
    ),
    sa.Column('process_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['streams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_sessions_uuid'), 'stream_sessions', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_sessions_uuid'), table_name='stream_sessions')
    op.drop_table('stream_sessions')
    # ### end Alembic commands ###
