"""add uuid to nodes

Revision ID: f63bfcbfad78
Revises: 96b12cfb691d
Create Date: 2026-07-26 21:24:13.651277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63bfcbfad78'
down_revision: Union[str, Sequence[str], None] = '96b12cfb691d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('uuid', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_nodes_uuid'), 'nodes', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_uuid'), table_name='nodes')
    op.drop_column('nodes', 'uuid')
    # ### end Alembic commands ###
